project:
  type: website
  output-dir: docs

website:
  title: "LASER"
  page-navigation: true
  repo-url: https://github.com/laser-institute/laser-website
  repo-actions: [edit, issue]
  favicon: "images/laser-icon.png"
  google-analytics: "G-6TQEEVEPKC"
  
  navbar:
    background: "#427E93"
    logo: "images/laser-icon.png"
    left:
      - href: index.qmd
        text: Home
      - href: institute-la.qmd
        text: Institute  
      - href: curriculum-orientation.qmd
        text: Curriculum
      - href: instruction-intro.qmd
        text: Instruction
    right:
      - icon: cloud-fill
        href: https://posit.cloud/spaces/493094/join?access_code=qjsumVzA0HZYgrxOSizVbVPmDs7iHYS32yUQaqDe
        aria-label: RStudio Cloud
      - icon: github
        href: https://github.com/laser-institute
  
  sidebar:
    style: "docked"
    search: true
    contents:
    - section: "Institute"
      contents:
        - institute-la.qmd
        - institute-goals.qmd
        - institute-components.qmd
        - curriculum-design.qmd
    - section: "Curriculum"
      contents:
        - curriculum-orientation.qmd
        - curriculum-la-workflow.qmd
        - curriculum-machine-learning.qmd
        - curriculum-network-analysis.qmd
        - curriculum-text-mining.qmd
        - curriculum-knowledge-tracing.qmd
    - section: "Instruction"
      contents:
        - instruction-intro.qmd
        - instruction-tech.qmd
        - instruction-course.qmd
        - instruction-workshop.qmd
    

  page-footer:
      left: "This page is built with [Quarto](https://quarto.org/) and hosted by [GitHub](https://pages.github.com)."
      background: "#427E93"
      right:
      - text: "License"
        href: LICENSE.md
      - text: "Code of Conduct"
        href: CODE_OF_CONDUCT.md  
  
format:
  html:
    theme: 
      light: cosmo
      dark: [cosmo, style/dark.scss]
    css: styles.css
    toc: true
    
editor: visual