---
title: "Module Content"
---

LASER modules cover a broad range of both introductory and advanced methods frequently leveraged by LA researchers and explicitly illustrate how these methods have been applied in STEM education research. Introductory modules will focus on basic proficiency with software tools commonly employed in LA and data science more broadly (i.e., R, Python, GitHub, APIs) and focus on topics pertaining to data-intensive research workflows (Krumm et al., 2018). These modules include learning activities focused on essential data wrangling processes, as well as exploratory techniques such as data visualizations and dashboards. Modules addressing advanced methods will focus on a range of modeling techniques including supervised machine learning (feature engineering, model tuning, and diagnostic metrics), unsupervised learning methods such as clustering, relationship mining methods such as association rule and sequential pattern mining, topic modeling, knowledge tracing and knowledge graphs, network analysis and the use of Application Programming Interfaces (APIs).

Interwoven within and across modules, and as appropriate to each method, are topics designed to deepen learners' understanding of LA approaches, applications, and legal and ethical issues. Specifically, topics will include but are not limited to reproducible research and open-science standards; types of data used in LA and the methods for their collection; applications of LA to STEM educational contexts such as recommendation and intelligent tutoring systems, adaptive learning and curriculum design, and students at risk of failing a course; and legal and ethical considerations such as student privacy, data ethics and algorithmic bias. In addition, learners are introduced to frameworks and approaches such as research-practice partnerships to prepare them to work closely with educational organizations to improve STEM outcomes at the local, district and state level.

|                              |                |                      |                                  |                          |
|--------------|--------------|--------------|----------------|--------------|
| **LA Workflows**             | Data Wrangling | Exploratory Analysis | Modeling Basics                  | Data Products            |
| **Supervised Learning (SL)** | SL Basics      | Feature Engineering  | Model Tuning                     | Diagnostic Metrics       |
| **Unsupervised Methods**     | UM Basics      | Clustering           | Factor Analysis                  | Knowledge Structures     |
| **Text Mining (TM)**         | TM Basics      | Topic Modeling       | Text Classification              | Large Language Models    |
| **Relationship Mining (RM)** | RM Basics      | Correlation Mining   | Association and Sequential Rules | Association Rule Metrics |
| **Knowledge Tracing (KT)**   | KT Basics      | BKT family           | PFA/LKT families                 | DKT family               |
| **Network Analysis (SNA)**   | SNA Basics     | Measurement          | Network Inference                | Epistemic Networks       |
