---
title: "Instructional Formats"
---

#### **Selecting a Format for Instructional Plans**

In addition to developing a SHARK Goal, scholars will select the format for their instruction. Formats will vary based on scholars’ SHARK Goal, which may include, but is not limited to, courses, webinars, and workshops. Scholars are encouraged to select formats that are appropriate for their institutional roles, contexts, expertise, professional goals and interests. For example, some scholars will want to incorporate LASER materials into an entire course that they teach. In this instance, a product for choosing a semester-long course would be to develop a course syllabus. Other scholars will wish to choose a format where the instructional plan will be implemented in one to four hours of instruction. There are many possibilities for choosing a one to four hour format. For example, some scholars may want to design an instructional plan for one or two classes during a course that they teach. Others may wish to design professional development for faculty and/or other colleagues at their home institution that they implement in the form of a workshop. Yet others may want to create professional development for colleagues at and beyond their home institution in the form of a virtual webinar. Another possibility is designing a presentation or workshop that is implemented at a professional conference. Scholars should be creative and select formats that work best for their goals and contexts.

#### **Planning During the Summer Institute**

Scholars will participate in daily Pedagogy and Design Sessions that will support them in creating an instructional plan. During the Summer Institute, templates will be provided to scholars to guide their planning. Scholars will use one of the following planning guides based on their SHARK Goal and selected format for implementation:

-   [Syllabus Instructional Plan](https://docs.google.com/document/d/1q4RXARFeWG5xmgTQhZxwDlFwhqyOvjR9QcpKOG39Cq0/edit#heading=h.1vjy6yaqjtfe)

-   [Instructional Plan (1-4 hrs)](https://docs.google.com/document/d/1QKIHpjJsnriMnWlHLFV0GFCELXyTmwDkRF3MOSWK5cE/edit)

#### **Refining Plans and Implementation During the Academic Year**

During the academic year, scholars will continue planning, refining and finalizing instructional plans that will be implemented during the academic year, preferably in the fall. Scholars will participate in monthly check-ins with the LASER BEAM team to finalize plans and implementation of instruction.

\
