---
title: "Syllabus Example"
---

## Introduction To Learning Analytics (ECI 586)

As the use of digital resources continues to expand in education, an unprecedented amount of new data is becoming available to educational researchers and practitioners. In response, Learning Analytics (LA) has emerged over the past decade as an interdisciplinary field encompassing Learning (e.g. educational technology, learning and assessment sciences), Analytics (e.g. visualization, computer/data sciences), and Human-Centered Design (e.g. usability, participatory design).

This course will provide students with an overview of the field, examples of its use in educational contexts, and applied experience with tools and techniques for analyzing new sources of data from new perspectives. As participants gain experience in the collection, analysis, and reporting of data throughout the course, they will be better prepared to help educational organizations understand and improve learning and the contexts in which learning occurs.

**Number of Credits:** 3

**Course Prerequisites/Co-requisites:** This course has no prerequisites.

**GitHub Repository**: <https://github.com/sbkellogg/eci-586>

## Time & Location

**Meeting Time:** This distance education course is predominantly asynchronous. Online tools are utilized throughout the course for communication and interaction. In addition, we will use Zoom for synchronous virtual office hours, web conferencing, or whole class discussions. For optional live class meet-ups, I will send out a poll the first week of class to find a time that works for the majority of students and record these meetings for students who are not able to attend.

**Virtual Class Locations:** All course materials and activities can be accessed online through NC State’s Moodle course management platform. Access <http://wolfware.ncsu.edu/> and log-in with your Unity ID and password. After logging-in, locate and click on ECI 586 An Introduction to Learning Analytics to access the course site.

Students must have Internet access and access to a Web browser (e.g., Safari, Firefox, Chrome) to participate in this course. The Moodle course site and Web-based software required for completing course projects may only be accessed online. It is strongly recommended that students have high-speed Internet access.

## Instructor Information

**Name:** [Dr. Shaun Kellogg](https://www.fi.ncsu.edu/people/sbkellog)\
**Email:** [shaun.kellogg\\\@ncsu.edu](https://sbkellogg.github.io/eci-586/shaun.kellogg@ncsu.edu)\
**Office:** [Friday Institute for Educational Innovation](https://www.fi.ncsu.edu/) (Room 223)\
**Phone:** (919) 513-8563\
**Hours:** Appointments by [Calendly](https://calendly.com/sbkellogg/analytics) Monday-Friday 8:00-4:00\
**Social:** [LinkedIn](https://www.linkedin.com/in/shaunbkellogg/) \| [GitHub](https://github.com/settings/profile)

## Course Texts

There are several required textbooks for this course, all of which are freely available online or through the NCSU Library. Supplemental course readings and content (e.g. articles, videos) will also be provided at no cost through the Moodle course site. You will also be asked to locate articles of interest for our discussions and I highly recommend that you link Google Scholar to the NCSU Library: <https://www.lib.ncsu.edu/articles/google-scholar>.

### Required

1.  Krumm, A., Means, B., & Bienkowski, M. (2018). [*Learning analytics goes to school: A collaborative approach to improving education.*](https://catalog.lib.ncsu.edu/catalog/NCSU4862134) Routledge.

2.  Estrellado, R. A., Freer, E. A., Mostipak, J., Rosenberg, J. M., & Velásquez, I. C. (2020). [*Data science in education using R*.](https://datascienceineducation.com/)Routledge.

3.  Lang, C., Siemens, G., Wise, A., & Gasevic, D. (Eds.). (2017). [*Handbook of learning analytics (2nd Edition)*](https://www.solaresearch.org/publications/hla-22/). New York, NY, USA: SOLAR, Society for Learning Analytics and Research.

4.  Carolan, B. V. (2013). [*Social network analysis and education: Theory, methods & applications*.](https://catalog.lib.ncsu.edu/catalog/NCSU2803782) Sage Publications.

### Optional

1.  Sclater, N. (2017). [*Learning analytics explained*](https://catalog.lib.ncsu.edu/catalog/NCSU4863297). Taylor & Francis.

2.  Xie, Y., Allaire, J. J., & Grolemund, G. (2018). [*R markdown: The definitive guide*.](https://bookdown.org/yihui/rmarkdown/) CRC Press.

3.  Wickham, H., & Grolemund, G. (2016). [*R for data science: import, tidy, transform, visualize, and model data (2e)*](https://r4ds.hadley.nz/). “ O’Reilly Media, Inc.”.

4.  Wickham, H. (2021). [*Mastering shiny*.](https://mastering-shiny.org/) “ O’Reilly Media, Inc.”.

5.  Healy, K. (2018). [*Data visualization: a practical introduction*.](http://socviz.co/) Princeton University Press.

6.  Cairo, A. (2016). [*The truthful art: Data, charts, and maps for communication*.](https://catalog.lib.ncsu.edu/catalog/NCSU3923006) New Riders.

## Software

Students should feel comfortable installing new software programs and navigating unfamiliar graphical user interfaces. It is also recommended that students in this class have some background knowledge of online learning environments (e.g. LMS, MOOCs, etc.).

### Required Software

This course requires R and R Studio, which will be used to provide hands-on experience with the concepts and skills addressed in course readings.

1.  **Posit Cloud** ([https://posit.co/products/cloud/cloud/)](https://posit.co/products/cloud/cloud/)) provides access to Posit’s powerful set of data science tools, the **RStudio IDE**([https://posit.co/products/open-source/rstudio](https://posit.co/products/open-source/rstudio/)), an integrated development environment (IDE) for R and Python that includes a console and syntax-highlighting editor, as well as tools for plotting, history, debugging, and workspace management. To register for a free Posit Cloud account vist: <https://login.posit.cloud/register.>

2.  **Posit Primers** (<https://posit.cloud/learn/primers>) provide an excellent series of interactive tutorials that range from R fundamentals like basic programming syntax to complex tasks like building interactive data dashboards.

3.  **RPubs** ([https://rpubs.com)](https://rpubs.com/)) is a free and easy web publishing platform for R. Throughout the course, you will be using R Markdown documents ([https://rmarkdown.rstudio.com/)](https://rmarkdown.rstudio.com/)), which weave together narrative text and code to produce elegantly formatted, static and dynamic outputs formats including: [HTML](https://bookdown.org/yihui/rmarkdown/html-document.html), [PDF](https://bookdown.org/yihui/rmarkdown/pdf-document.html), [HTML5 slides](https://bookdown.org/yihui/rmarkdown/ioslides-presentation.html), [Tufte-style handouts](https://bookdown.org/yihui/rmarkdown/tufte-handouts.html), [books](https://bookdown.org/), [dashboards](https://rmarkdown.rstudio.com/flexdashboard/), [shiny applications](https://bookdown.org/yihui/rmarkdown/shiny-documents.html), [research articles](https://github.com/rstudio/rticles), [websites](https://bookdown.org/yihui/rmarkdown/rmarkdown-site.html), and more. To publish these documents via RPubs, however, you will first need to create an account here: <https://rpubs.com/users/new.>

### Optional Software

1.  **R** ([https://www.r-project.org](https://www.r-project.org/)) is an open-source language and computing environment for data manipulation, analysis, and visualization. Installation files for Windows, Mac, and Linux can be found at the website for the Comprehensive R Archive Network, <http://cran.r-project.org/>.

2.  **RStudio Desktop** ([https://posit.co/products/open-source/rstudio)](https://posit.co/products/open-source/rstudio)) is a free desktop application of the RStudio IDE for R that runs on Windows, MacOS or Linux. Its advantages over Posit Cloud include offline access, full control over the local environment, customization options, data privacy and security, and the ability to leverage the full resources of your local machine, such as CPU, memory, and storage. While we will be using RStudio through Posit Cloud for this course, I eventually recommend shifting to RStudio Desktop if you plan to use R and RStudio beyond this course.

3.  **Posit** **Cheat Sheets** (<https://posit.cloud/learn/cheat-sheets>) also provide handy reference to commonly used packages and their essential functions, including example code for testing them out.

4.  **Dataquest** ([https://www.dataquest.io](https://www.dataquest.io/)) offers interactive R, Python, Sheets, SQL and shell courses on topics in data science, statistics and machine learning. An email will be sent providing free access to our Dataquest team, full catalogue of courses and resources for 6 months.

5.  **LinkedIn Learning** ([https://www.linkedin.com/learning)](https://www.linkedin.com/learning) offers tutorials and training courses on R, R Studio, and Tableau. LinkedIn Learning is [available at no charge to students](https://www.lib.ncsu.edu/faq/what-is-linkedin-learning). 

6.  **Git** is a free and open source distributed version control system. Jenny Bryan’s very thorough installation and R Studio set up process for Mac and Windows can be found here: [http://happygitwithr.com](http://happygitwithr.com/).

7.  **GitHub** is a web-based hosting service for version control using Git. You can create an account here: [https://github.com](https://github.com/)

## Course Goals

Goals for the Introduction to Learning Analytics course are guided by the North Carolina State University motto: ***Think and Do***. Specifically, goals for this course are twofold:

-   **Disciplinary Knowledge.** Students will deepen their understanding of Learning Analytics as an emerging approach within the field of Learning Analytics, including its application in a wide range of education settings.

-   **Technical Skills.** Scholars will develop proficiency with the processes, tools, and techniques necessary to efficiently, effectively, and ethically apply Learning Analytics for understanding and improving learning and the contexts in which learning occurs.

## Student Learning Outcomes

The following learning objectives are aligned with the overarching objectives of the Graduate Certificate in Learning Analytics program and are embedded in each unit of the course. Students who complete this course will be able to:

-   **Conceptual Foundations:** Describe Learning Analytics as a discipline (e.g. history, concepts, theories, methodologies, stakeholders, legal and ethical issues) and how it has been applied to important problems, questions, and issues in education;

-   **Data Sources & Measures:** Identify and appropriately use educational data sources (e.g. Student Information and Learning Management Systems) and key student metrics;

-   **Tool Proficiency:** Efficiently and effectively apply up-to-date software and tools (i.e. R or Tableau) to implement Learning Analytics workflows for preparing, analyzing, and sharing data;

-   **Processes & Techniques**: Understand and apply data visualization approaches and techniques (e.g. interactive visualization and data dashboards) in order to understand and improve learning and the contexts in which learning occurs; and,

-   **Communication:** Clearly communicate methods, analyses, findings, and recommendations that can provide actionable insight into learning contexts for a range of education stakeholders.

## Course Structure & Schedule

This course is divided into four units focused on conceptualizing Learning Analytics as a research discipline and developing the foundational skills for data exploration using a range of digital data sources. The first week of each unit introduces terminology, core concepts, and applications of Learning Analytics through readings, course videos, and discussion. In the second week, we focus on developing essential technical skills necessary for data-intensive Research workflows through R software tutorials. In the third week of each unit, we apply these skills to conduct an analysis and create a data product using publicly available educational datasets.

| **Schedule** | **Topics**                                                                                                                                                                                                                         |
|--------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **WELCOME**  | **OVERVIEW & INTRODUCTIONS**                                                                                                                                                                                                       |
| Week 1       | Introductions, syllabus review, and software setup                                                                                                                                                                                 |
| **UNIT 1**   | **WHAT IS LEARNING ANALYTICS?**                                                                                                                                                                                                    |
| Week 2       | **Readings & Discussion:** Introduction to Learning Analytics as a discipline, including a little history, key concepts, learning theories, methodologies, etc.)                                                                   |
| Week 3       | **R Toolkit Tutorial**: Software tutorials on critical packages and key functions used to import, wrangle, explore, model, and report “tidy” data.                                                                                 |
| Week 4       | **Case Study**: A look into student-level data from online classes provided by a state-wide virtual public school.                                                                                                                 |
| **UNIT 2**   | **PARTNERSHIPS & PREDICTIVE ANALYTICS**                                                                                                                                                                                            |
| Week 5       | **Readings & Discussion:** An examination of the use of data visualization and dashboards in Learning Analytics to understand and improve student learning.                                                                        |
| Week 6       | **R Toolkit Tutorial**: A deeper dive into the “grammar of graphics” and development of foundational skills for creating interactive data apps.                                                                                    |
| Week 7       | **Case Study**: An exploration of aggregate student data to examine educational inequities and changes over time.                                                                                                                  |
| **UNIT 3**   | **TEXT AS DATA**                                                                                                                                                                                                                   |
| Week 8       | **Readings & Discussion:** Introduction to text mining in education, including a key concepts and common techniques, and their application in educational settings.                                                                |
| Week 9       | **R Toolkit Tutorial**: An introduction to the Shiny package and development of interactive data apps.                                                                                                                             |
| Week 10      | **Case Study**: A focus on text processing, word frequencies, and sentiment lexicons to examine public opinions on Twitter around the Common Core and Next Generation Science Standards.                                           |
| **UNIT 4**   | **A NETWORK PERSPECTIVE**                                                                                                                                                                                                          |
| Week 11      | **Readings & Discussion:** Introduction to social network analysis in education, including a key concepts and common techniques, and applications in educational settings.                                                         |
| Week 12      | **R Toolkit Tutorial**: Software tutorials on critical packages and key functions used to import, wrangle, explore, model, and report relational data.                                                                             |
| Week 13      | **Case Study**: A focus on network data formats, descriptives, and sociograms to examine peer interaction in Massively Open Online Course for Educators (MOOC-Eds).                                                                |
| **WRAP UP**  | **MAKE UP & FINAL PROJECTS**                                                                                                                                                                                                       |
| Week 14      | **Make-up Week:** Final opportunity for students to complete any missing work. This week should also be used to make significant progress on your final project.                                                                   |
| Week 15      | **Final Project:** In lieu of a final exam, students will complete and Independent analysis and develop a data product (e.g. report, presentation, data dashboard, etc.) that demonstrates concepts learned throughout the course. |

## Major Assignments & Assessment

1.  **Housekeeping (4 pts)**: Students will review the syllabus and “sign” the Online Learner Agreement sent at the beginning of the semester that outlines expectations for participating in an online course. Student will also be required to install necessary software and post a brief introduction of themselves and respond to their peers. 

2.  **Reading & Discussion (24 pts)**: The first week of each unit introduces terminology, core concepts, and applications of an analytical approach through readings, course videos, and discussion. To help guide discussions, students are provided a set of essential questions to address and are also encouraged to explore their own areas of interest. The primary goal of course readings and discussion is to foster a deeper understanding of how Learning Analytics has been applied in educational contexts.

3.  **R Toolkit Tutorials (24 pts):** The second week of each unit, consists of tutorials for working with R packages and functions used import, wrangle, explore, and model data. The primary goal of these tutorials is to support familiarity and fluency with R syntax and key functions for data analysis.

4.  **Case Studies (24 pts)**: In the third week of each unit, students will complete an interactive “case study” demonstrating how key data-intensive research workflow processes (i.e., wrangling, visualizing, summarizing, modeling, and communicating data) featured in exemplary education research studies are implemented in R. Coding case studies also provide a holistic setting to explore important foundational LA topics integral to data analysis such as reproducible research, use of APIs, ethical considerations, diversity and inclusion, and creation of useful data products.

5.  **Final Project (24 pts)**: In lieu of a final exam, students will conduct and independent analysis using a data source of their choosing and create a “data product” (e.g. report, presentation, data dashboard, etc.) demonstrating the knowledge and skills gained throughout the semester.

**Grading Scale:** The grading scale is based on 100 points:

A+ (97-100), A (94-96), A- (90-93), B+ (87-89), B (84-86), B- (80-83)

C+ (77-79), C (74-76), C- (70-73), D+ (67-69), D (64-66), D- (60-63), F (59 or less)

Late work is accepted but may be penalized at 15% per week it is late. Assignments submitted by the due date, however, may be revised and resubmitted for a higher grade by the following week. Students experiencing unforeseen circumstances with a resulting excused absence (e.g., family medical emergency) are allowed to make up work without penalty.

**Course Feedback Expectations:** Please contact your instructor via email (shaun.kellogg\\\@ncsu.edu) with any questions about the course project or other assignments. Your instructor will strive to answer any emails within 24 hours (M-F) and 48 hours on the weekend, and grade submitted assignments within 5-7 days of the due date. In addition, students will be provided ongoing opportunities, and are strongly encouraged, to provide course feedback to help improve the design of current and future course implementations. 

## NC State Policies

**Academic Integrity:** Students are bound by the academic integrity policy as stated in the code of student conduct. Therefore, students are required to uphold the university pledge of honor and exercise honesty in completing any assignment. See the website for a full explanation: <http://www.ncsu.edu/policies/student_services/student_discipline/POL11.35.1.php>

**N.C. State University Policies, Regulations, and Rules (PRR)**: Students are responsible for reviewing the PRRs which pertain to their course rights and responsibilities. These include:

-   <http://policies.ncsu.edu/policy/pol-04-25-05> (Equal Opportunity and Non-Discrimination Policy Statement),

-   <http://oied.ncsu.edu/oied/policies.php>  (Office for Institutional Equity and Diversity),

-   <http://policies.ncsu.edu/policy/pol-1135-01> (Code of Student Conduct), and

-   <http://policies.ncsu.edu/regulation/reg-02-50-03> (Grades and Grade Point Average).

**University Non-Discrimination Policies:** It is the policy of the State of North Carolina to provide equality of opportunity in education and employment for all students and employees. Accordingly, the university does not practice or condone unlawful discrimination in any form against students, employees or applicants on the grounds of race, color, religion, creed, sex, national origin, age, disability, or veteran status. In addition, North Carolina State University regards discrimination based on sexual orientation to be inconsistent with its goal of providing a welcoming environment in which all its students, faculty, and staff may learn and work up to their full potential.

**Disabilities**: Reasonable accommodations will be made for students with verifiable disabilities. In order to take advantage of available accommodations, students must register with the Disability Resource Office at Holmes Hall, Suite 304, Campus Box 7509, 919-515-7653. For more information on NC State’s policy on working with students with disabilities, please see the Academic Accommodations for Students with Disabilities Regulation (REG02.20.01).

## Other Important Resources

-   **Keep Learning:** <https://dasa.ncsu.edu/students/keep-learning/>

-   **Protect the Pack FAQs:** <https://www.ncsu.edu/coronavirus/frequently-asked-question>

-   **NC State Protect the Pack Resources for Students:** [Resources for Students \| Protect the Pack](https://www.ncsu.edu/coronavirus/reactivating-campus/resources-for-students/)

-   **NC State Keep Learning, tips for students opting to take courses remotely:** [Keep Learning Tips for Remote Learning](https://dasa.ncsu.edu/students/keep-learning/)

-   **Introduction to Zoom for students:** <https://youtu.be/5LbPzzPbYEw>

-   **Learning with Moodle, a student’s guide to using Moodle:** <https://moodle-projects.wolfware.ncsu.edu/course/view.php?id=226>

-   **NC State Libraries** [Technology Lending Program](https://www.lib.ncsu.edu/devices)

This site is open source. [Improve this page](https://github.com/sbkellogg/eci-586/edit/main/README.md).
